name: Release

on:
  push:
    paths:
      - 'app/version.py'
  workflow_dispatch:

permissions:
  contents: write

env:
  QT_QPA_PLATFORM: offscreen 

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -U "https://yt-dlp.github.io/Pyinstaller-Builds/x86_64/pyinstaller-6.7.0-py3-none-any.whl"

      - name: Build application
        working-directory: ./app
        run: |
          pyinstaller --onefile --clean --name=yt-dlp-gui -y app.py --icon ./ui/assets/yt-dlp-gui.ico --noconsole --add-data "./config/config.json:." --exclude-module "**/*.git" --exclude-module "**/__cache__" --exclude-module "**/dist" --exclude-module "**/build"
          Compress-Archive -Path dist/* -DestinationPath yt-dlp-gui-win64.zip

      - name: Get version
        working-directory: ./app
        run: echo "VERSION=$(python -c "from version import __version__; print(__version__)")" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ./app/yt-dlp-gui-win64.zip
